# -*- coding: utf-8 -*-
"""LLM-text classification.ipynb

Automatically generated by Colab.

"""

!pip install -U transformers
!pip install -U sentencepiece
!pip install -U sacremoses

from transformers import pipeline
import pandas as pd



"""## Image segmentation"""

url = "https://imgs.search.brave.com/ZSTgS0eaNczlmky2u5Jh7rWlO4Ir0MGJV8DQsT1zr5U/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvdGh1/bWJuYWlscy8wMDMv/MzYzLzQ0MS9zbWFs/bC9wb3J0cmFpdC1v/Zi1oYW5kc29tZS1n/dXktc21pbGluZy1p/bi10aGUtYXV0dW1u/LXBhcmstZnJlZS1w/aG90by5qcGc"

image = Image.open(requests.get(url, stream=True).raw)

segmenter = pipeline("image-segmentation", model="mattmdjaga/segformer_b2_clothes")

outputs = segmenter(image)

outputs

outputs[0]['mask']

outputs[1]['mask']

outputs[2]['mask']

outputs[3]['mask']

outputs[4]['mask']

