# -*- coding: utf-8 -*-
"""LLM-text classification.ipynb

Automatically generated by Colab.

"""

!pip install -U transformers
!pip install -U sentencepiece
!pip install -U sacremoses

from transformers import pipeline
import pandas as pd

classifier = pipeline("text-classification", model ="SamLowe/roberta-base-go_emotions")

text = "i love you"
outputs = classifier = classifier(text)
pd.DataFrame(outputs)

